### ISSUE TITLE
Demo not working. Errors after install and placing the 

### ISSUE THREAD

**Issue by exocode** [lwhiteley/react-push-menu#19]
I expect following the docs in the example folder (npm install && npm start) would show the demo. Maybe you have to update them?

Also installing in my app I fall into some issues. ..like "react-items" are not included in the package.json but are used in the examples (why are they mandatory? Users should be able to choose their library. Are you willing to provide a codesandbox.io example?

thank you very much in advance

PS: Feature request: reverse sliding direction from right to left :-)

**Comment by exocode** [comment]
to run example I run `npm run start-example` and end up with `Module not found: Can't resolve './reactComponentLib' in '/Users/jan/Downloads/react-push-menu-master/example/src'
`

**Comment by exocode** [comment]
or here: 
```
❯ npm run dev

> react-push-menu@3.1.2 dev /Users/jan/Downloads/react-push-menu-master
> run-p build-watch start-example

internal/modules/cjs/loader.js:783
    throw err;
    ^

Error: Cannot find module 'shell-quote'
Require stack:
- /Users/jan/Downloads/react-push-menu-master/node_modules/npm-run-all/lib/index.js
- /Users/jan/Downloads/react-push-menu-master/node_modules/npm-run-all/bin/run-p/main.js
- /Users/jan/Downloads/react-push-menu-master/node_modules/npm-run-all/bin/common/bootstrap.js
- /Users/jan/Downloads/react-push-menu-master/node_modules/npm-run-all/bin/run-p/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/jan/Downloads/react-push-menu-master/node_modules/npm-run-all/lib/index.js:13:20)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jan/Downloads/react-push-menu-master/node_modules/npm-run-all/lib/index.js',
    '/Users/jan/Downloads/react-push-menu-master/node_modules/npm-run-all/bin/run-p/main.js',
    '/Users/jan/Downloads/react-push-menu-master/node_modules/npm-run-all/bin/common/bootstrap.js',
    '/Users/jan/Downloads/react-push-menu-master/node_modules/npm-run-all/bin/run-p/index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-push-menu@3.1.2 dev: `run-p build-watch start-example`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-push-menu@3.1.2 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jan/.npm/_logs/2020-07-29T13_53_38_331Z-debug.log

```

**Comment by lwhiteley** [comment]
ill check these later today, been meaning to do some maintenance on the example app.

Thanks

**Comment by exocode** [comment]
@lwhiteley Originally I was searching for exactly that one: http://www.jq22.com/demo/jquery-sliding-menu-master/ (as you can see the sliding direction is more "naturally". Maybe you can keep that "wish" in mind *blink blink* :-)

**Comment by MahdiKarimipour** [comment]
@lwhiteley, nice work on the menu, it would be great if you could unblock the example. The below issue still happens:

Module not found: Can't resolve './reactComponentLib' in '/Users/jan/Downloads/react-push-menu-master/example/src'

**Comment by MahdiKarimipour** [comment]
> 
> 
> @lwhiteley, nice work on the menu, it would be great if you could unblock the example. The below issue still happens:
> 
> Module not found: Can't resolve './reactComponentLib' in '/Users/jan/Downloads/react-push-menu-master/example/src'

Run "pretest" before running the app, which will generate the reactComponentLib.

**Comment by lwhiteley** [comment]
yes im aware sorry.. i have very little time to address it.. what's left is to fix the typescript validation in the branch

**Comment by MahdiKarimipour** [comment]
Thanks, I understand, 

The working example is different to the demo you have in your readme, in terms of styling and animation (i.e. it will need work to be presentable in a prod application.) Can I confirm if that's expected or I am missing some css?

**Comment by lwhiteley** [comment]
The cast is actually missing for animation.
There are two related open issues to resolve it

**Comment by silas-v1** [comment]
> > @lwhiteley, nice work on the menu, it would be great if you could unblock the example. The below issue still happens:
> > Module not found: Can't resolve './reactComponentLib' in '/Users/jan/Downloads/react-push-menu-master/example/src'
> 
> Run "pretest" before running the app, which will generate the reactComponentLib.

I don't see a "pretest" script.  Could you elaborate on the steps to generate `reactComponentLib`?
